#!/bin/ksh
#
# $Revision: 1.1 $ $Date: 2019-01-21 01:05:30-05 $
# $Source: /home/vogelke/notebook/2019/0120/vim-templates/RCS/newvim,v $
# $Host: furbag.my.domain $
# $UUID: adc8f7f2-b9d9-493a-9301-7404d118898b $
#
#<newvim: insert a template if we have a matching extension

export PATH=/usr/local/bin:/bin:/usr/bin

case "$#" in
    0) exit 0 ;;
    *) file="$1" ;;
esac

test -f "$file" && exec /bin/ksh "$file"
exit 0
